// <auto-generated />
namespace OWASP_Top10_TampaDay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FirstChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201410302100157_FirstChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
